### ISSUE TITLE
Installation on Windows

### ISSUE THREAD

**Issue by stulacy** [nicolaroberts/hdp#1]
I'm having trouble installing this package on a Windows 8 machine. The `devtools::install_github("nicolaroberts/hdp", build_vignettes = TRUE)` instruction produces the following error: 

> creating vignettes ...Warning: running command '"C:/PROGRA~1/R/R-33~1.1/bin/x64/Rscript" --vanilla --default-packages= -e "tools::buildVignettes(dir = '.', tangle = TRUE)"' had status 3
>  ERROR

I cloned the repository to try and investigate it further and found that the problem was in building the vignette, in particular the call in `general.Rmd` to `hdp_posterior`, which in turns calls a native C function. 

Removing the vignette still doesn't work, as it seems to have a problem compiling the DLL. The error message output from running `devtools::install` from within my local repository is

> *\* testing if installed package can be loaded
> **\* arch - i386
> **\* arch - x64
> Error in inDL(x, as.logical(local), as.logical(now), ...) : 
>   unable to load shared object 'H:/RLibrary/hdp/libs/x64/hdp.dll':
>   LoadLibrary failure:  %1 is not a valid Win32 application.

I'm running 64-bit R, with both the 64-bit and 32-bit gcc versions that come with Rtools in my PATH, with the 64-bit version first, I've also tried 32-bit R with 32-bit gcc first in my PATH but no combinations seem to work.

**Comment by ShangyiLuo** [comment]
I encountered the same problem, how do you deal with it

**Comment by stulacy** [comment]
Unfortunately I didn't manage to get it working.

**Comment by lincj1994** [comment]
I managed to install and run it in Ubuntu virtual machine.
